### ISSUE TITLE
Text elements should be children of item that contain them. 

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#161]
Right now they are stored in text but in fact 
this looks bogus.

```
(MicroDownParser parse: '- item1 **bold**
- item 2') children first children first children isEmpty 
>>> true 
```
and this is not nice.

**Comment by kasperosterbye** [comment]
You mean that the `MicListItemBlock` should not have a field `text`, but an array of `MicInlineElement`s in its `children`?

**I think this is a good idea**, in particular there is a class `MicTextBlock` which precisely is subclass of `MicInlineElement.

I have a feeling that this issue is also the case for the caption of urls and images. Perhaps elsewhere as well.

**Comment by Ducasse** [comment]
I do not remember exactly :). 
Now I wanted to see what is the invariant that child/parent should hold. And after we have different ways to implement either  children are kept in a collection and  children instance variable, or they are in specific instance variables but we still get a children method so that we can iterate them all). 

I'm not sure to be clear, but from an API point of view I would like to have 
- a way to access a given child
- a way to access all children

**Comment by kasperosterbye** [comment]
I have run into this topic also in designing AST. At one abstraction level an if-statement has 2-3 children, at an other level it has a condition, a true part and an optional else-part.

The way I handle that is getter and setter for `condition`, which just manipulates first child. I have used this two-level abstraction in multiple situations. 

However, in the concrete situation I believe the field `text` misleading as it does not contain a string, but a collection of `MicInlineElement`. 

I will try to make a PR for this.

**Comment by Ducasse** [comment]
Have a look at what we did

we have for eg always tried to have
- caption = the text
- captionElements -> the elements

we have header and headerElements, 
text and textElements, 

So may be we missed some but we started to follow this convention elements should be returned with xElements messages.

And this independently of the internal representation (children vs. direct field).

**Comment by kasperosterbye** [comment]
Yes, that one is clear. But your original issue is that the "captionElements" are not part of the children. Now I have looked at this all morning, and it seems quite clear that it is not the case anywhere in the system.  Most (I have not looked at all) blocks have a text field for the text up til the arrival of any nested blocks.

In all tests I have seen you do access the item-text using `textElements`. That is, your original example should according the the conventions I have seen be written as:

```smalltalk
(MicroDownParser parse: '- item1 **bold**
- item 2') children first children first textElements isEmpty 
```
rather than:

```smalltalk
(MicroDownParser parse: '- item1 **bold**
- item 2') children first children first children isEmpty 
```

**Comment by kasperosterbye** [comment]
Besides, adding the textElements to the front of the children will make it necessary to scan children for nested lists. Any nested list is currently accessed using children - and this is used in alot of tests `children first` being all over the tests.

One option is then to pack the textElements into a `MicParagraphBlock` during closeMe. That way all the textElements will be inside the first child consistently. However, this will need to be done to all blocks, and a lot of tests must be updated to go `children second` instead of `children first`

**Comment by Ducasse** [comment]
Thanks for your analysis. I do not have the big picture.
Right now I'm trying to provide a clear path resolution and I'm fighting to new lecture and reporting :)
So my concentration is limited.

**Comment by kasperosterbye** [comment]
Quite OK. I will not work on this issue any further as I now consider it a major rewrite with limited improvement in quality of code.

**Comment by kasperosterbye** [comment]
Children are now better implemented
