### ISSUE TITLE
ListItem children are empty while textElements are used

### ISSUE THREAD

**Issue by lgrangaud** [pillar-markup/Microdown#247]
and the following method smells strange

```
visitListItem: anItem

	anItem textElements do: [ :each | each accept: self ].
	self flag: #toCheck. "textelemenets are the children so this is strqnge to hqve in aadition"
	self visitChildrenOf: anItem
```

**Comment by kasperosterbye** [comment]
I believe this is a similar issue to #161. There is a longer discussion at that issue. Maybe you could clarify if it is the same issue, or what the difference is?

**Comment by Ducasse** [comment]
I will address this point once I'm done fixing the PR of Lyna. 
The idea is that listItem should use children to store their children and not text.

**Comment by kasperosterbye** [comment]
I believe that the orginal structure is this:
* this is the text stored in text elements (remember it can have structure because of bold, links etc)
   * and this entire indented list is a child propper
   * including this item

I believe the "children" was originally used to store children only of paragraph level blocks, and the other attributes came out of the inline blocks. 

Having looked at it now again, it is most certainly the same as issue #161, and the comments I wrote there still stands.

**Comment by Ducasse** [comment]
Yes I think this is related too. 
I think the rule is simple and it is any MicElement down the tree should be accessible via children and may be if we want other methods. 
All the rest is a kind of attributes that is not part of the children structure.

**Comment by Ducasse** [comment]
I close it since this issue is done with my latest commit [18ecb97] 18ecb979a8c28f63620f73f1b7d9b43057d8ca5d
